#!/bin/bash
# NEXUS PL - GitHub Pages Quick Setup

echo "🚀 NEXUS PL - GitHub Pages Setup Guide"
echo "=========================================="
echo ""
echo "✅ Projekt jest w pełni gotowy!"
echo ""
echo "📋 OPCJA 1: Development Lokalne"
echo "--------------------------------"
echo "npm run dev"
echo "Otwórz: http://localhost:5173/"
echo ""
echo "📋 OPCJA 2: Wdrażanie Manualne"
echo "--------------------------------"
echo "npm run build     # Budowanie"
echo "npm run deploy    # Wdrażanie na GitHub Pages"
echo ""
echo "📋 OPCJA 3: GitHub Actions (RECOMMENDED)"
echo "----------------------------------------"
echo "1. Utwórz repozytorium na GitHub: https://github.com/new"
echo "2. Pushnij kod:"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit'"
echo "   git branch -M main"
echo "   git remote add origin https://github.com/YOU/nexus-dashboard.git"
echo "   git push -u origin main"
echo "3. Włącz GitHub Pages:"
echo "   - Settings → Pages"
echo "   - Source: Deploy from a branch"
echo "   - Branch: gh-pages"
echo "   - Save"
echo "4. GitHub Actions automatycznie wdroży projekt!"
echo ""
echo "📚 Dokumentacja:"
echo "- README.md - Pełna dokumentacja"
echo "- DEPLOYMENT.md - Szczegółowy przewodnik wdrażania"
echo ""
echo "🎨 Customizacja:"
echo "- src/dashboard.ts - HTML dashboard"
echo "- index.html - Tailwind config"
echo "- src/style.css - CSS"
echo ""
